#!/bin/bash
# For executing this script run "./dws-dev-001-bash"
# Reading input 
read -p "Enter your input: " input

# Creating array from input
input_array=($input)

# This function is for iteration N times and wait for N Seconds, the run "command_run" function again
function iteration_func {
	for i in $(seq ${input_array[4]}); do
		sleep ${input_array[2]}
	    command_run
	     if [[ $? -eq 0 ]]; then
			exit 0	
		fi		
	done
}

# This function will execute "flask app test"
function command_run {
	$(${input_array[5]} ${input_array[6]} ${input_array[7]})
}

# Calling "command_run" function
command_run

# Checking the "command_run" function behaviour
# If it is true exit 0, else go and run "iteration_func" function
if [[ $? -eq 0 ]]; then
	exit 0
else 
	iteration_func	
fi
	
# Finally if "iteration_func" does not exit 0, print an error and exit 1
echo "We have an error!!!!"
$(false)
echo $?
exit 0
