#!/bin/bash
# For executing this script run "./dws-dev-001-bash"

# This function is for iteration N times and wait for N Seconds run "command_run" again
function iteration_func {
	for i in $(seq $TRY_NUMBER); do
		sleep $TRY_INTERVAL
	    command_run
	    if [[ $? -eq 0 ]]; then
			exit 0	
		fi		
	done
}

# This function will execute "flask app test"
function command_run {
	$TRY_COMMAND
}

# Reading input 
read -p "Enter your input: " input

# Creating array from input
input_array=($input)

flask=${input_array[5]}
app=${input_array[6]}
test=${input_array[7]}
TRY_COMMAND="$flask $app $test"
TRY_NUMBER=${input_array[4]}
TRY_INTERVAL=${input_array[2]}

# Calling "command_run" function
command_run

# Checking the "command_run" function behaviour
# If it is true exit 0, else go and run "iteration_func" function
if [[ $? -eq 0 ]]; then
	exit 0
else 
	iteration_func	
fi
	
# Finally if "iteration_func" does not exit 0, print an error and exit 1
echo "We have an error!!!!"
$(false)
>&2 echo $? 
#exit 0
